# serverless.yml

name: "blackislandaudio"

plugins:
  - serverless-dotenv-plugin

app:
  component: "@sls-next/serverless-component@1.18.0" # it is recommended you pin the latest stable version of serverless-next.js
  inputs:
    domain: ["blackislandaudio.com"]
